name: Build libmodbus

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-libmodbus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up cross-compiler
      uses: dawidd6/action-download-artifact@v6
      with:
        repo: coolitsystemsinc/cdu-build
        github_token: ${{ secrets.ACTIONS_AUTH }}        
        workflow: musl-artifact.yaml
        workflow_conclusion: success
        name: arm-linux-musleabihf-cross
        allow_forks: true
        path: .

    - name: Copy cross-compiler to usr folder
      run: |
        tar -xvf arm-linux-musleabihf-cross.tgz
        sudo cp -r ./arm-linux-musleabihf-cross/* /usr/

    - name: Compile libmodbus
      run: |
        chmod +x *
        ./autogen.sh
        mkdir -p library
        
        ./configure ac_cv_func_malloc_0_nonnull=yes --host=arm-linux-musleabihf --prefix=/usr/arm-linux-musleabihf/ 
        sudo make install
    
    - name: Upload libmodbus.so
      uses: actions/upload-artifact@v4
      with:
        name: libmodbus
        path: |
          /usr/arm-linux-musleabihf/lib/libmodbus.so*
          /usr/arm-linux-musleabihf/include/modbus*
