name: Build libmodbus

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-libmodbus:
    name: Run cross-compiler download and verification for each architecture
    strategy:
      matrix:
        arch:
          - arm-linux-musleabihf
          #- aarch64-linux-musl

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Download musl-cross-compiler library from release
      id: musl-cross-compiler
      uses: robinraju/release-downloader@v1.8
      with:
        repository: coolitsystemsinc/cdu-lib
        latest: true
        token: ${{ secrets.ACTIONS_AUTH }}
        fileName: "${{ matrix.arch }}-cross.tgz"
        extract: false
        out-file-path: .
        
    - name: Copy cross-compiler to usr folder
      run: |
        tar -xvf ${{ matrix.arch }}-cross.tgz
        sudo cp -r ./${{ matrix.arch }}-cross/* /usr/

    - name: Compile libmodbus
      run: |
        chmod +x *
        ./autogen.sh
        mkdir -p library
        
        ./configure ac_cv_func_malloc_0_nonnull=yes --host=${{ matrix.arch }} --prefix=/usr/${{ matrix.arch }}/ 
        sudo make install
    
    - name: Upload libmodbus.so
      uses: actions/upload-artifact@v4
      with:
        name: libmodbus${{ matrix.arch == 'aarch64-linux-musl' && '-64' || '' }}
        path: |
          /usr/${{ matrix.arch }}/lib/libmodbus.so*
          /usr/${{ matrix.arch }}/include/modbus*
